version: "1"

volumes:
  postgres_data:

services:
  postgresql:
    image: postgis/postgis:12-master
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: thunkable
